title: Privacy Policies
description: Privacy policies for our mobile applications
baseurl: "/privacy-policy-manager"
url: "https://jatin-shihora.github.io"

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM

# Exclude from processing
exclude:
  - README.md
  - .gitignore
  - assets
